# Generated by Django 4.1.7 on 2023-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Логин')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('online', models.DateTimeField(verbose_name='Последнее посещение')),
            ],
        ),
    ]
