# Generated by Django 4.1.7 on 2023-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('scenarist', models.CharField(max_length=100, verbose_name='Сценарист')),
                ('stars', models.CharField(max_length=100, verbose_name='Звезды')),
                ('pg', models.CharField(max_length=100, verbose_name='Возрастной рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publish_date', models.DateField(verbose_name='Дата выхода')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('rates_count', models.PositiveIntegerField(verbose_name='Количество отзывов')),
                ('rates_sum', models.PositiveIntegerField(verbose_name='Сумма оценок')),
                ('trailer_url', models.CharField(max_length=250, verbose_name='URL Трейлера')),
                ('poster_url', models.CharField(max_length=250, verbose_name='URL Постера')),
                ('url', models.CharField(max_length=250, verbose_name='URL Фильма')),
                ('reviews', models.JSONField()),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.PositiveBigIntegerField(verbose_name='Фильм')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('rate', models.PositiveIntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
